# docker-compose.yml

version: '3.8'

services:
  # Nginx
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - springboot-service

  # Spring Boot
  springboot-service:
    build:
      context: ./SpringBoot
      dockerfile: Dockerfile
    container_name: eium-springboot-app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      flask-service:
        condition: service_started
    environment:
      - FLASK_INTERNAL_URL=http://flask-service:5000
    volumes:
      - ./SpringBoot/build/classes:/app/classes
      - ./SpringBoot/build/resources:/app/resources

  flask-service:
    build:
      context: ./Flask
      dockerfile: Dockerfile
    container_name: eium-flask-app
    volumes:
      - ./Flask:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    env_file:
      - ./.env
  db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: